general:
  random_seed: 3333

data:
  processed_numpy_file: '../data/processed_sheets_numpy/data.pkl'
  data_augmentation: true

model:
  lstm_layers: 3
  lstm_dim: 512
  batch_size: 64
  data_dim: 192

hyperparams:
  sequence_length: 100
  learning_rate: 0.001
  optimiser: 'adam'